# Generated by Django 4.1.3 on 2023-03-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactor',
            name='experience',
            field=models.SmallIntegerField(choices=[(0, 'beginner'), (1, 'midlevel'), (2, 'expert')], default=0),
        ),
    ]
